const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const about = fs.readFileSync(path.join(root, "about.html"), "utf8");
const styles = fs.readFileSync(path.join(root, "styles.css"), "utf8");
const script = fs.readFileSync(path.join(root, "script.js"), "utf8");
const bioPhoto = fs.readFileSync(path.join(root, "assets", "bio-graduation-family.jpg"));

assert.match(about, /id="coursework-title"[^>]*>Coursework map\./, "about page should replace the range section with coursework");
assert.match(about, /data-education-map/, "about page should include an interactive education map wrapper");
assert.equal((about.match(/data-education-node=/g) || []).length, 5, "coursework map should expose five phase controls");
assert.equal((about.match(/data-course-panel=/g) || []).length, 5, "coursework map should expose five matching panels");
assert.doesNotMatch(about, /transcript course titles|private records stay off the public site/, "coursework map should not expose the old private-source note");
assert.doesNotMatch(about, /class="coursework-mentors"|Faculty and instructors|Henry Farrell/, "coursework map should replace the faculty chip list with a progression chart");
assert.match(about, /class="academic-progression"[\s\S]*data-academic-progression[\s\S]*Realms of Knowledge[\s\S]*Fields over time\./, "coursework map should include a Realms of Knowledge progression chart");
assert.doesNotMatch(about, /Academic progression/, "progression chart label should use the requested Realms of Knowledge copy");
assert.equal((about.match(/data-progression-series=/g) || []).length, 5, "progression chart should plot five academic field series");
assert.equal((about.match(/data-progression-field=/g) || []).length, 5, "progression chart should expose five interactive field keys");
assert.equal((about.match(/data-progression-note=/g) || []).length, 5, "progression field keys should carry short interactive summaries");
assert.match(about, /data-progression-field="systems"[\s\S]*AI systems/, "progression chart should include the current AI systems field");
assert.match(about, /class="coursework-lenses"[\s\S]*Power[\s\S]*Society[\s\S]*Evidence[\s\S]*Systems/, "coursework lenses should be integrated into the board");
assert.doesNotMatch(about, /Institutions are not abstract to me/, "removed bio statement should stay removed");
assert.doesNotMatch(about, /class="stack reveal"[\s\S]*large-statement/, "bio layout should not keep an empty statement column");
assert.match(about, /class="split-layout bio-layout">\s*<figure class="bio-photo reveal"[\s\S]*assets\/bio-graduation-family\.jpg[\s\S]*Umar Zafar in graduation robes standing with his mentor Lana/, "bio section should start with the requested public photo in the compact bio layout");
assert.match(about, /I am Umar; next to me is my kind mentor Lana\./, "bio photo should identify Umar and Lana in the caption");
assert.doesNotMatch(about, /mentor Lane/, "bio photo should not keep the misspelled mentor name");
assert.match(about, /political theory, human rights, development, and sustainability/, "bio copy should present the broader intellectual range");
assert.match(about, /SAIS and through Daadras[\s\S]*export controls, cybersecurity, infrastructure resilience, AI governance/, "bio copy should connect Daadras to the technology policy range");
assert.doesNotMatch(about, /I do not treat research, writing, and building as separate identities/, "removed bio paragraph should stay removed");
assert.doesNotMatch(bioPhoto.subarray(0, 512).toString("latin1"), /Exif/, "published bio photo should not retain source EXIF metadata");
assert.match(about, /Political Economy of AI/, "coursework map should include SAIS AI policy coursework");
assert.match(about, /Research Methodology/, "coursework map should include undergraduate methods coursework");
assert.match(about, /World Order and Disorder/, "coursework map should include SAIS order and security coursework");
assert.doesNotMatch(about, /Working range\./, "old range heading should be removed");
assert.doesNotMatch(about, /class="coursework-evolution"/, "coursework lenses should not render as a separate box row");

assert.match(styles, /\.coursework-board\s*\{/, "coursework board styles should exist");
assert.match(styles, /\.coursework-grid\s*\{[\s\S]*gap:\s*0;[\s\S]*align-items:\s*stretch;[\s\S]*border:\s*1px solid var\(--rule\)/, "coursework section should render as one balanced framed module");
assert.match(styles, /\.coursework-grid > \.feature-copy\s*\{[\s\S]*border-right:\s*1px solid var\(--rule\)/, "coursework left narrative panel should divide cleanly from the board");
assert.match(styles, /\.coursework-board\s*\{[\s\S]*grid-template-rows:\s*auto auto auto;[\s\S]*align-content:\s*start/, "coursework board should not stretch the active course panel into an empty vertical void");
assert.match(styles, /\.coursework-panel\s*\{[\s\S]*min-height:\s*0/, "coursework panels should size to their content");
assert.match(styles, /@media \(max-width: 980px\)[\s\S]*\.coursework-grid\s*\{[\s\S]*grid-template-columns:\s*1fr/, "coursework module should stack before it becomes cramped");
assert.match(styles, /\.coursework-node\.is-active/, "coursework active node styles should exist");
assert.match(styles, /\.coursework-lenses\s*\{/, "coursework lens footer styles should exist");
assert.match(styles, /\.section-title\s*\{[\s\S]*grid-column:\s*1 \/ 5/, "shared section headings should align to the left grid edge");
assert.match(styles, /\.bio-layout\s*\{[\s\S]*grid-template-columns:\s*minmax\(220px,\s*340px\) minmax\(320px,\s*680px\);[\s\S]*justify-content:\s*start/, "bio layout should use a left-aligned photo and copy band");
assert.match(styles, /\.bio-layout \.rich-copy\s*\{[\s\S]*grid-column:\s*2/, "bio copy should sit directly beside the photo");
assert.match(styles, /\.bio-photo\s*\{[\s\S]*grid-column:\s*1/, "bio photo should start the bio content at the left edge");
assert.match(styles, /\.bio-photo\s*\{[\s\S]*border:\s*1px solid var\(--rule\)/, "bio photo should use the site frame language");
assert.match(styles, /\.bio-photo img\s*\{[\s\S]*height:\s*clamp\(260px,\s*22vw,\s*360px\)/, "bio photo should not render at its intrinsic image height");
assert.match(styles, /\.bio-photo figcaption\s*\{[\s\S]*font-family:\s*var\(--font-mono\)/, "bio photo caption should use quiet metadata styling");
assert.match(styles, /@media \(max-width: 1180px\)[\s\S]*\.bio-layout\s*\{[\s\S]*grid-template-columns:\s*minmax\(210px,\s*320px\) minmax\(0,\s*1fr\)/, "bio layout should tighten to two columns before medium-width clipping starts");
assert.match(styles, /@media \(max-width: 720px\)[\s\S]*\.bio-layout\s*\{[\s\S]*grid-template-columns:\s*1fr/, "bio layout should stack on mobile");
assert.match(styles, /\.nav-menu--projects \.nav-menu__panel\s*\{[\s\S]*min-width:\s*218px/, "project dropdown should stay compact enough to avoid overlap");
assert.match(styles, /\.nav-menu__panel a\s*\{[\s\S]*min-height:\s*30px;[\s\S]*font-size:\s*12px/, "dropdown items should use smaller text and tighter rows");
assert.match(styles, /\.nav-menu\.is-open \.nav-menu__panel/, "dropdowns should support controlled open state");
assert.match(styles, /\.academic-progression\s*\{/, "progression chart card styles should exist");
assert.match(styles, /\.academic-progression\s*\{[\s\S]*grid-template-columns:\s*minmax\(128px,\s*0\.74fr\) minmax\(176px,\s*1fr\)/, "progression chart should use a compact desktop grid");
assert.match(styles, /@media \(max-width: 720px\)[\s\S]*\.academic-progression\s*\{[\s\S]*grid-template-columns:\s*1fr/, "progression chart should stack cleanly on mobile");
assert.match(styles, /\.progression-line\s*\{[\s\S]*stroke-linecap:\s*round/, "progression lines should render as smooth minimal curves");
assert.match(styles, /\.progression-summary\s*\{[\s\S]*max-height:\s*62px;[\s\S]*-webkit-line-clamp:\s*4/, "progression summary should stay compact enough to avoid a tall empty module");
assert.match(styles, /\.academic-progression\.has-active \.progression-series/, "progression chart should support an active interaction state");
assert.doesNotMatch(styles, /\.coursework-evolution\s*\{/, "old coursework evolution box styles should be removed");
assert.match(styles, /\.contact-mosaic \.contact-mosaic-copy\s*\{[\s\S]*grid-column:\s*1 \/ 4/, "about contact mosaic should align left");

assert.match(script, /function initEducationMaps\(\)/, "coursework interaction initializer should exist");
assert.match(script, /querySelectorAll\("\[data-education-map\]"\)/, "script should bind education maps by data attribute");
assert.match(script, /initEducationMaps\(\);/, "coursework interaction should be initialized on load");
assert.match(script, /function initAcademicProgressionCharts\(\)/, "progression chart interaction initializer should exist");
assert.match(script, /querySelectorAll\("\[data-academic-progression\]"\)/, "script should bind academic progression charts by data attribute");
assert.match(script, /\.progression-summary/, "progression chart should target the live summary text, not legend buttons");
assert.match(script, /dataset\.progressionNote/, "progression chart should read field notes from legend buttons");
assert.match(script, /initAcademicProgressionCharts\(\);/, "progression chart interaction should be initialized on load");
assert.match(script, /closeOtherMenus\(menu\)/, "nav menu opening should close sibling dropdowns");
assert.match(script, /menu\.classList\.toggle\("is-open", isExpanded\)/, "nav menu script should own the visible dropdown state");

console.log("about coursework ok");
